# Generated by Django 4.2.1 on 2023-05-30 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("split", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
