# Generated by Django 4.2.1 on 2023-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0003_alter_expense_created_at_lender_borrower"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="expense_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="lender",
            name="expense_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
