# Generated by Django 4.2.1 on 2023-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
