# Generated by Django 4.2.1 on 2023-06-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0001_initial"),
        ("activites", "0002_activities_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="expense",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="split.expense",
            ),
        ),
    ]
